version: '3'

services:
  nginx:
    build: ./nginx
    volumes:
      - ${APP_ROOT}/web/build:/var/www/public
    ports:
      - 80:80
    depends_on:
      - auth
      - english

  auth:
    build: ../services/auth
    volumes:
      - ${APP_SERVICES_ROOT}/auth:/var/www/services/auth
      - /var/www/services/auth/node_modules
    expose:
      - 8000
    environment:
      PORT: 8000

  english:
    build: ../services/english
    volumes:
      - ${APP_SERVICES_ROOT}/english:/var/www/services/english
      - /var/www/services/english/node_modules
    expose:
      - 8080
    environment:
      PORT: 8080